# Generated by Django 6.0.3 on 2026-06-12 12:10

import veiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/banners/', validators=[veiculos.models.validate_tamanho_banner]),
        ),
    ]
