# Generated by Django 6.0.3 on 2026-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_alter_evento_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('tipo', models.CharField(choices=[('youtube', 'YouTube'), ('soundcloud', 'SoundCloud')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Set',
                'verbose_name_plural': 'Sets',
                'ordering': ['-data', 'nome'],
            },
        ),
    ]
